name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install pip --upgrade
          if grep version pyproject.toml | grep -q "dev";
            then pip install https://github.com/fiduswriter/fiduswriter/archive/develop.zip;
            else pip install https://github.com/fiduswriter/fiduswriter/archive/main.zip;
          fi
          if grep version pyproject.toml | grep -q "dev";
            then pip install https://github.com/fiduswriter/fiduswriter-books/archive/develop.zip;
            else pip install https://github.com/fiduswriter/fiduswriter-books/archive/main.zip;
          fi
      - uses: pre-commit/action@v3.0.1
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install pip --upgrade
          if grep version pyproject.toml | grep -q "dev";
            then pip install https://github.com/fiduswriter/fiduswriter/archive/develop.zip;
            else pip install https://github.com/fiduswriter/fiduswriter/archive/main.zip;
          fi
          if grep version pyproject.toml | grep -q "dev";
            then pip install https://github.com/fiduswriter/fiduswriter-books/archive/develop.zip;
            else pip install https://github.com/fiduswriter/fiduswriter-books/archive/main.zip;
          fi
          cd fiduswriter
          mv ../ci/configuration.py ./
          mv ../ci/.coveragerc ./
          pip install requests[security]
          pip install coverage
          pip install coveralls
          pip install packaging
          pip install webdriver-manager
          pip install selenium
          coverage run $(which fiduswriter) setup --no-static
      - name: Run tests
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 8
          max_attempts: 3
          retry_on: error
          command: |
            cd fiduswriter
            coverage run $(which fiduswriter) test gitrepo_export
      - name: Coveralls
        run: |
            cd fiduswriter
            coverage combine
            coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
